language: elixir

cache:
  directories:
  - priv/plts
  - deps

elixir:
  - 1.10.2

otp_release:
  - 22.0

before_script:
  - epmd -daemon

script:
  - mix format --check-formatted
  - mix test --include distributed
  - travis_wait 30 mix dialyzer
